In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Embedding, LSTM
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split

from tensorflow.keras import backend as K
def root_mean_squared_error(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))
import csv

In [33]:
f = open("DIAMOND_I_10_data.csv")
rdr = csv.reader(f)
r = list(rdr)
f.close()

label = []
sentences = []
for R in r[1:]:
    _sentences = ""
    for i, _R in enumerate(R):
        __R = _R.replace("[", "").replace("]", "").replace("'", "").replace(" ", "")
        if i > 0 and i != 4 and len(__R) > 0:
            __R = __R.split(",")
            __R = "-".join(__R[:2] + sorted(__R[2:]))
            _sentences += __R + " "
        try:    
            if i == 4:
                label.append(int(__R))
        except:
            pass
    sentences.append(_sentences)

data = pd.DataFrame(zip(sentences, label), columns = ['sentence', 'label'])

In [34]:
enumerate(R)

In [6]:
x_data, y_data = data['sentence'], data['label']
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=0, stratify=y_data)

In [7]:
print(x_train[0])

TFT6_Augment_PortableForge TFT6_Augment_Distancing TFT6_Augment_SunfireBoard TFT7_Lillia-2-noItems-noItems-noItems TFT7_Shen-2-TFT_Item_ZekesHerald-noItems-noItems TFT7_Braum-2-noItems-noItems-noItems TFT7_Nunu-2-noItems-noItems-noItems TFT7_Olaf-3-TFT7_Item_AssassinEmblemItem-TFT_Item_InfinityEdge-TFT_Item_RunaansHurricane TFT7_Diana-3-TFT4_Item_OrnnZhonyasParadox-TFT_Item_FrozenHeart-TFT_Item_IonicSpark TFT7_Yasuo-1-TFT_Item_JeweledGauntlet-TFT_Item_Quicksilver-TFT_Item_SeraphsEmbrace TFT7_Bard-1-TFT_Item_SpearOfShojin-noItems-noItems 


In [8]:
tokenizer = Tokenizer(filters = '', lower = False)
tokenizer.fit_on_texts(x_train)
word_dic = tokenizer.word_index
word_count = tokenizer.word_counts
sequences = tokenizer.texts_to_sequences(x_train)
x_train_encoded = pad_sequences(sequences, maxlen = 16, padding = 'post')
vocab_size = len(word_dic) + 1

In [9]:
print(x_train_encoded)

[[  6 153 151 ...   0   0   0]
 [212 233  18 ...   0   0   0]
 [  7  19  45 ...   0   0   0]
 ...
 [303  81 116 ...   0   0   0]
 [142  23  58 ...   0   0   0]
 [ 69  23  49 ...   0   0   0]]


In [10]:
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length = 16))
model.add(LSTM(32, activation = 'tanh'))
model.add(Dense(1))
model.compile(loss = 'mse', optimizer = 'adam')
history = model.fit(x_train_encoded, y_train, epochs=30, batch_size=5, validation_split=0.2)

NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported